"""initial schema (8.3)

Revision ID: 140c83845744
Revises:
Create Date: 2026-08-16 04:25:13.174440

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "140c83845744"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "backtest_daily_nav",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("trade_date", sa.String(length=10), nullable=False),
        sa.Column("strategy_nav", sa.Float(), nullable=False),
        sa.Column("benchmark_nav", sa.Float(), nullable=True),
        sa.Column("cash", sa.Float(), nullable=False),
        sa.Column("positions_value", sa.Float(), nullable=False),
        sa.Column("total_value", sa.Float(), nullable=False),
        sa.Column("drawdown", sa.Float(), nullable=False),
        sa.Column("open_positions", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "trade_date", name="uq_nav_run_date"),
    )
    op.create_index(
        op.f("ix_backtest_daily_nav_run_id"), "backtest_daily_nav", ["run_id"], unique=False
    )
    op.create_index("ix_nav_run", "backtest_daily_nav", ["run_id"], unique=False)
    op.create_table(
        "fills",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("order_id", sa.String(length=64), nullable=False),
        sa.Column("strategy_snapshot_id", sa.Integer(), nullable=True),
        sa.Column("fill_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("side", sa.String(length=16), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("volume", sa.Float(), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("commission", sa.Float(), nullable=False),
        sa.Column("stamp_tax", sa.Float(), nullable=False),
        sa.Column("transfer_fee", sa.Float(), nullable=False),
        sa.Column("slippage_cost", sa.Float(), nullable=False),
        sa.Column("total_fee", sa.Float(), nullable=False),
        sa.Column("order_api", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_fills_order", "fills", ["order_id"], unique=False)
    op.create_index(op.f("ix_fills_order_id"), "fills", ["order_id"], unique=False)
    op.create_index(op.f("ix_fills_run_id"), "fills", ["run_id"], unique=False)
    op.create_index("ix_fills_run_time", "fills", ["run_id", "fill_time"], unique=False)
    op.create_index(
        op.f("ix_fills_strategy_snapshot_id"), "fills", ["strategy_snapshot_id"], unique=False
    )
    op.create_table(
        "order_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("order_id", sa.String(length=64), nullable=False),
        sa.Column("event_type", sa.String(length=24), nullable=False),
        sa.Column("event_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("qty", sa.Float(), nullable=False),
        sa.Column("price", sa.Float(), nullable=True),
        sa.Column("info_json", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_events_order", "order_events", ["order_id"], unique=False)
    op.create_index("ix_events_run_time", "order_events", ["run_id", "event_time"], unique=False)
    op.create_index(op.f("ix_order_events_order_id"), "order_events", ["order_id"], unique=False)
    op.create_index(op.f("ix_order_events_run_id"), "order_events", ["run_id"], unique=False)
    op.create_table(
        "orders",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("order_id", sa.String(length=64), nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("strategy_snapshot_id", sa.Integer(), nullable=True),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("side", sa.String(length=16), nullable=False),
        sa.Column("style", sa.String(length=24), nullable=False),
        sa.Column("qty", sa.Float(), nullable=False),
        sa.Column("limit_price", sa.Float(), nullable=True),
        sa.Column("order_api", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("eligible_fill_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("time_in_force", sa.String(length=8), nullable=False),
        sa.Column("remaining_qty", sa.Float(), nullable=False),
        sa.Column("filled_qty", sa.Float(), nullable=False),
        sa.Column("avg_fill_price", sa.Float(), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reject_reason", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("order_id"),
    )
    op.create_index("ix_orders_run_code", "orders", ["run_id", "code"], unique=False)
    op.create_index(op.f("ix_orders_run_id"), "orders", ["run_id"], unique=False)
    op.create_index("ix_orders_run_submitted", "orders", ["run_id", "submitted_at"], unique=False)
    op.create_index(
        op.f("ix_orders_strategy_snapshot_id"), "orders", ["strategy_snapshot_id"], unique=False
    )
    op.create_table(
        "strategy_snapshot",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("file_name", sa.String(length=255), nullable=False),
        sa.Column("code_text", sa.Text(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("line_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_strategy_snapshot_sha256"), "strategy_snapshot", ["sha256"], unique=True
    )
    op.create_table(
        "backtest_run",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("task_name", sa.String(length=255), nullable=False),
        sa.Column("platform", sa.String(length=32), nullable=False),
        sa.Column("strategy_snapshot_id", sa.Integer(), nullable=False),
        sa.Column("parent_run_id", sa.String(length=64), nullable=True),
        sa.Column("params_json", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("manifest_hash", sa.String(length=64), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_log", sa.Text(), nullable=True),
        sa.Column("zquant_version", sa.String(length=32), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["strategy_snapshot_id"],
            ["strategy_snapshot.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_backtest_run_parent_run_id"), "backtest_run", ["parent_run_id"], unique=False
    )
    op.create_index(
        op.f("ix_backtest_run_strategy_snapshot_id"),
        "backtest_run",
        ["strategy_snapshot_id"],
        unique=False,
    )
    op.create_index("ix_run_platform", "backtest_run", ["platform"], unique=False)
    op.create_index("ix_run_status_started", "backtest_run", ["status", "started_at"], unique=False)
    op.create_table(
        "backtest_metrics",
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("metrics_json", sa.Text(), nullable=False),
        sa.Column("metrics_version", sa.String(length=16), nullable=False),
        sa.Column("computed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["backtest_run.id"],
        ),
        sa.PrimaryKeyConstraint("run_id"),
    )
    op.create_table(
        "run_manifest",
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("manifest_json", sa.Text(), nullable=False),
        sa.Column("manifest_hash", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["backtest_run.id"],
        ),
        sa.PrimaryKeyConstraint("run_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("run_manifest")
    op.drop_table("backtest_metrics")
    op.drop_index("ix_run_status_started", table_name="backtest_run")
    op.drop_index("ix_run_platform", table_name="backtest_run")
    op.drop_index(op.f("ix_backtest_run_strategy_snapshot_id"), table_name="backtest_run")
    op.drop_index(op.f("ix_backtest_run_parent_run_id"), table_name="backtest_run")
    op.drop_table("backtest_run")
    op.drop_index(op.f("ix_strategy_snapshot_sha256"), table_name="strategy_snapshot")
    op.drop_table("strategy_snapshot")
    op.drop_index(op.f("ix_orders_strategy_snapshot_id"), table_name="orders")
    op.drop_index("ix_orders_run_submitted", table_name="orders")
    op.drop_index(op.f("ix_orders_run_id"), table_name="orders")
    op.drop_index("ix_orders_run_code", table_name="orders")
    op.drop_table("orders")
    op.drop_index(op.f("ix_order_events_run_id"), table_name="order_events")
    op.drop_index(op.f("ix_order_events_order_id"), table_name="order_events")
    op.drop_index("ix_events_run_time", table_name="order_events")
    op.drop_index("ix_events_order", table_name="order_events")
    op.drop_table("order_events")
    op.drop_index(op.f("ix_fills_strategy_snapshot_id"), table_name="fills")
    op.drop_index("ix_fills_run_time", table_name="fills")
    op.drop_index(op.f("ix_fills_run_id"), table_name="fills")
    op.drop_index(op.f("ix_fills_order_id"), table_name="fills")
    op.drop_index("ix_fills_order", table_name="fills")
    op.drop_table("fills")
    op.drop_index("ix_nav_run", table_name="backtest_daily_nav")
    op.drop_index(op.f("ix_backtest_daily_nav_run_id"), table_name="backtest_daily_nav")
    op.drop_table("backtest_daily_nav")
    # ### end Alembic commands ###
